package com.dawes.modelo;
// Generated 27-ene-2018 16:42:27 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Itinerario generated by hbm2java
 */
@Entity
@Table(name = "itinerario", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Itinerario implements java.io.Serializable {

	private Integer iditinerario;
	private String nombre;
	private String categoria;
	private String duracion;
	private String ubicacion;
	private Set<Parada> paradas = new HashSet<Parada>(0);

	
	
	
	
	@Override
	public String toString() {
		return "Itinerario [iditinerario=" + iditinerario + ", nombre=" + nombre + ", categoria=" + categoria
				+ ", duracion=" + duracion + ", ubicacion=" + ubicacion + ", paradas=" + paradas + "]";
	}

	public Itinerario() {
	}

	public Itinerario(String nombre) {
		this.nombre = nombre;
	}

	public Itinerario(String nombre, String categoria, String duracion, String ubicacion, Set<Parada> paradas) {
		this.nombre = nombre;
		this.categoria = categoria;
		this.duracion = duracion;
		this.ubicacion = ubicacion;
		this.paradas = paradas;
	}
	public Itinerario(Integer iditinerario, String nombre, String categoria, String duracion, String ubicacion, Set<Parada> paradas) {
		this.iditinerario = iditinerario;
		this.nombre = nombre;
		this.categoria = categoria;
		this.duracion = duracion;
		this.ubicacion = ubicacion;
		this.paradas = paradas;
	}
	public Itinerario(Integer iditinerario, String nombre, String categoria, String duracion, String ubicacion) {
		this.iditinerario = iditinerario;
		this.nombre = nombre;
		this.categoria = categoria;
		this.duracion = duracion;
		this.ubicacion = ubicacion;
	
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "iditinerario", unique = true, nullable = false)
	public Integer getIditinerario() {
		return this.iditinerario;
	}

	public void setIditinerario(Integer iditinerario) {
		this.iditinerario = iditinerario;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "categoria", length = 45)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	@Column(name = "duracion", length = 15)
	public String getDuracion() {
		return this.duracion;
	}

	public void setDuracion(String duracion) {
		this.duracion = duracion;
	}

	@Column(name = "ubicacion", length = 45)
	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "itinerario")
	public Set<Parada> getParadas() {
		return this.paradas;
	}

	public void setParadas(Set<Parada> paradas) {
		this.paradas = paradas;
	}

}
